### ISSUE TITLE
Celery Error for Simultanous Jobs

### ISSUE THREAD

**Issue by psavery** [OpenChemistry/openchemistrypy#80]
When I run the notebook, it seems to be fairly common that an error *might* occur if multiple calculations are submitted at the same time. The following is the celery_command output when the error happens (note the `assetstore with that name already exists` part - I think that may be key).

```
[2019-05-20 22:57:58,419: INFO/Worker-4] Processing the output of the container description job.
[2019-05-20 22:57:58,450: WARNING/Worker-4] b'{"field": "name", "message": "An assetstore with that name already exists.", "type": "validation"}'
[2019-05-20 22:57:58,488: ERROR/Worker-4] Exception raise by task.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/cumulus/cumulus/taskflow/__init__.py", line 117, in wrapped
    return func(celery_task, *args, **kwargs)
  File "/openchemistrypy/taskflows/taskflows/__init__.py", line 282, in postprocess_description
    upload_job_output_to_folder(cluster, description_job, girder_token=task.taskflow.girder_token)
  File "/cumulus/cumulus/tasks/job.py", line 778, in upload_job_output_to_folder
    assetstore_id = get_assetstore_id(girder_token, cluster)
  File "/cumulus/cumulus/transport/files/__init__.py", line 54, in get_assetstore_id
    check_status(r)
  File "/cumulus/cumulus/common/__init__.py", line 32, in check_status
    request.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 928, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://girder:8080/api/v1/sftp_assetstores
[2019-05-20 22:57:58,497: ERROR/MainProcess] Task taskflows.postprocess_description[7d9f0313-824d-4076-8d30-ad3eb2d233bc] raised unexpected: HTTPError('400 Client Error: Bad Request for url: http://girder:8080/api/v1/sftp_assetstores',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/cumulus/cumulus/taskflow/__init__.py", line 117, in wrapped
    return func(celery_task, *args, **kwargs)
  File "/openchemistrypy/taskflows/taskflows/__init__.py", line 282, in postprocess_description
    upload_job_output_to_folder(cluster, description_job, girder_token=task.taskflow.girder_token)
  File "/cumulus/cumulus/tasks/job.py", line 778, in upload_job_output_to_folder
    assetstore_id = get_assetstore_id(girder_token, cluster)
  File "/cumulus/cumulus/transport/files/__init__.py", line 54, in get_assetstore_id
    check_status(r)
  File "/cumulus/cumulus/common/__init__.py", line 32, in check_status
    request.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 928, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://girder:8080/api/v1/sftp_assetstores
```

**Comment by psavery** [comment]
By the way, I still get this error, but I realized that it only happens if you submit several calculations simultaneously, and no other calculations have been done yet on the server. So it only occurs for the first set of calculations on the server, and only if multiple are submitted at once.

**Comment by psavery** [comment]
So, in order to avoid this issue, when I start up a fresh server, I always submit one job and wait for it to finish before proceeding to submit others simultaneously.

**Comment by alesgenova** [comment]
I'm trying to investigate this.
When you say "submit multiple calculations", do you mean several calculations in a single taskflow, or one calculation per taskflow?

**Comment by psavery** [comment]
@alesgenova Sorry, I should have clarified. I meant one calculation per taskflow. So, submitting multiple taskflows at the same time.

**Comment by alesgenova** [comment]
Thanks for the clarification!
I think I have tracked down the problem, I'm gonna implement a fix in `cumulus` to solve this

**Comment by psavery** [comment]
@alesgenova Unfortunately, I tried it out recently, and it looks like the problem didn't go away (jobs still fail if you submit many at once before any other jobs have been submitted), but the error has changed. You can see an example of the new error below.
```
celery_command_1  | [2020-02-11 19:43:31,998: ERROR/MainProcess] Task taskflows.postprocess_description[f406fb31-88d6-4d5d-b443-e8ef093e2c6a] raised unexpected: HTTPError('403 Client Error: Forbidden for url: http://girder:8080/api/v1/assetstore?limit=9223372036854775807',)
celery_command_1  | Traceback (most recent call last):
celery_command_1  |   File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 240, in trace_task
celery_command_1  |     R = retval = fun(*args, **kwargs)
celery_command_1  |   File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 438, in __protected_call__
celery_command_1  |     return self.run(*args, **kwargs)
celery_command_1  |   File "/cumulus/cumulus/taskflow/__init__.py", line 117, in wrapped
celery_command_1  |     return func(celery_task, *args, **kwargs)
celery_command_1  |   File "/openchemistrypy/taskflows/taskflows/__init__.py", line 287, in postprocess_description
celery_command_1  |     upload_job_output_to_folder(cluster, description_job, girder_token=task.taskflow.girder_token)
celery_command_1  |   File "/cumulus/cumulus/tasks/job.py", line 778, in upload_job_output_to_folder
celery_command_1  |     assetstore_id = get_assetstore_id(girder_token, cluster)
celery_command_1  |   File "/cumulus/cumulus/transport/files/__init__.py", line 78, in get_assetstore_id
celery_command_1  |     check_status(r)
celery_command_1  |   File "/cumulus/cumulus/common/__init__.py", line 32, in check_status
celery_command_1  |     request.raise_for_status()
celery_command_1  |   File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
celery_command_1  |     raise HTTPError(http_error_msg, response=self)
celery_command_1  | requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: http://girder:8080/api/v1/assetstore?limit=9223372036854775807

```
